### ISSUE TITLE
Place project source to the project without zip

### ISSUE THREAD

**Issue by pavelbinar** [rokudev/remote-debugger#2]
Hi Jonathan,

I can see from the git history that you had the Python files in here and then you deleted them and put them back in the `zip` file. Is there a reason for that?

I don't think it is good practice - no-one can browse the code, use it after the repository clone not even pull request it.

Please put the source back without the `zip`.

Thank you.

**Comment by jduval23** [comment]
I believe we wanted to provide a simple packaging of all of the source files to help save developers a few steps. You can certainly still download and extract the zip file to check out all the source files.

**Comment by pavelbinar** [comment]
Can we discuss that?

The `zip` file have several issues:

## Adding more friction to use this tool

Currently, to use this tool you have to:

1) clone the project - this is product for developers, developers clone the repositories
2) extract the file
3) run the file

The step 2 is unnecessary.

## If you wan to provide the one file `zip` then make the release

Github Releases are automatically ziped so you can download them without using git - that can be linked right from the README.

## Unable to track the source code

I cannot comment out or anyhow reference the source since it is actually hidden for git - so this basically disables the purpose of GIT = source code tracking. 

## Unable to do any pull requests

Just another side effect of the black box `zip`

## You are blocking the code to be searchable

Is that an intention?
